import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.56.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Simplified full-import row: only Name is required. School defaults to
// 'Independent' if blank. Email and Phone are optional.
// Everything else (login code/password, serial number, seat role, party,
// committee, constituency, state/city) is generated by the app.
interface StudentData {
  name: string;
  school?: string;
  email?: string;
  phone?: string;
  // scores-only mode fields
  serialNumber?: number;
  preeventScores?: number;
}

// The app's 6 operational zones (see src/lib/regions.ts ZONES) and the
// states that fall into each. Students at an event in one zone get
// constituencies drawn from the OTHER 5 zones — purely flavour data for the
// simulation, not a real electoral mapping.
type ZoneId = 'north' | 'east' | 'west' | 'northeast' | 'south_tn' | 'south_other';

const ZONE_STATES: Record<ZoneId, string[]> = {
  north: ['Delhi', 'Haryana', 'Punjab', 'Himachal Pradesh', 'Uttarakhand', 'Jammu and Kashmir', 'Ladakh', 'Uttar Pradesh', 'Rajasthan', 'Chandigarh'],
  east: ['West Bengal', 'Odisha', 'Bihar', 'Jharkhand', 'Andaman and Nicobar Islands'],
  west: ['Maharashtra', 'Gujarat', 'Goa', 'Madhya Pradesh', 'Chhattisgarh', 'Dadra and Nagar Haveli and Daman and Diu'],
  northeast: ['Assam', 'Meghalaya', 'Manipur', 'Mizoram', 'Nagaland', 'Tripura', 'Arunachal Pradesh', 'Sikkim'],
  south_tn: ['Tamil Nadu', 'Puducherry'],
  south_other: ['Telangana', 'Karnataka', 'Kerala', 'Andhra Pradesh', 'Lakshadweep'],
};

const STATE_TO_ZONE: Record<string, ZoneId> = (() => {
  const map: Record<string, ZoneId> = {};
  (Object.keys(ZONE_STATES) as ZoneId[]).forEach(zone => ZONE_STATES[zone].forEach(state => { map[state] = zone; }));
  return map;
})();

function getZoneId(state?: string | null): ZoneId | null {
  return state ? STATE_TO_ZONE[state] ?? null : null;
}

// Cities used as constituency seeds, grouped by zone.
// Actual Lok Sabha constituency names grouped by zone (~430 total).
// Sized so all zones combined far exceed the largest expected event.
const ZONE_CITIES: Record<ZoneId, string[]> = {
  north: [
    // Delhi (7)
    'Chandni Chowk', 'North East Delhi', 'East Delhi', 'New Delhi', 'North West Delhi', 'West Delhi', 'South Delhi',
    // UP (80)
    'Varanasi', 'Lucknow', 'Kanpur', 'Allahabad', 'Agra', 'Mathura', 'Meerut', 'Ghaziabad', 'Noida', 'Bareilly',
    'Gorakhpur', 'Moradabad', 'Saharanpur', 'Muzaffarnagar', 'Rampur', 'Aligarh', 'Hathras', 'Firozabad',
    'Mainpuri', 'Etah', 'Badaun', 'Aonla', 'Pilibhit', 'Shahjahanpur', 'Kheri', 'Dhaurahra', 'Sitapur',
    'Hardoi', 'Unnao', 'Mohanlalganj', 'Rae Bareli', 'Amethi', 'Sultanpur', 'Pratapgarh', 'Farrukhabad',
    'Etawah', 'Kannauj', 'Kanpur Dehat', 'Jhansi', 'Jalaun', 'Hamirpur', 'Banda', 'Fatehpur', 'Kaushambi',
    'Phulpur', 'Deoria', 'Bansgaon', 'Lalganj', 'Azamgarh', 'Ghosi', 'Salempur', 'Ballia', 'Ghazipur',
    'Chandauli', 'Mirzapur', 'Sant Kabir Nagar', 'Kushinagar', 'Maharajganj', 'Ambedkar Nagar',
    'Bahraich', 'Shrawasti', 'Gonda', 'Domariyaganj', 'Basti', 'Jaunpur', 'Machhlishahr',
    // Rajasthan (25)
    'Jaipur', 'Jaipur Rural', 'Jodhpur', 'Udaipur', 'Kota', 'Bikaner', 'Ajmer', 'Alwar', 'Bharatpur',
    'Karauli-Dholpur', 'Dausa', 'Sikar', 'Jhunjhunu', 'Churu', 'Sriganganagar', 'Bikaner', 'Nagaur',
    'Tonk-Sawai Madhopur', 'Bhilwara', 'Rajsamand', 'Banswara', 'Chittorgarh', 'Pali', 'Barmer', 'Jalor',
    // Haryana (10)
    'Ambala', 'Kurukshetra', 'Sirsa', 'Hisar', 'Karnal', 'Sonipat', 'Rohtak', 'Bhiwani-Mahendragarh', 'Faridabad', 'Gurugram',
    // Punjab (13)
    'Amritsar', 'Ludhiana', 'Jalandhar', 'Patiala', 'Chandigarh', 'Bathinda', 'Firozpur', 'Gurdaspur',
    'Hoshiarpur', 'Anandpur Sahib', 'Fatehgarh Sahib', 'Faridkot', 'Sangrur',
    // HP, UK, J&K
    'Shimla', 'Mandi', 'Hamirpur', 'Kangra', 'Dehradun', 'Haridwar', 'Tehri Garhwal', 'Almora', 'Nainital', 'Haldwani',
    'Srinagar', 'Jammu', 'Udhampur', 'Anantnag-Rajouri', 'Baramulla', 'Ladakh', 'Leh', 'Yamunanagar',
  ],
  east: [
    'Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Darbhanga', 'Kolkata', 'Howrah', 'Asansol', 'Siliguri',
    'Bhubaneswar', 'Cuttack', 'Ranchi', 'Jamshedpur', 'Dhanbad', 'Port Blair',
    'Durgapur', 'Malda', 'Bardhaman', 'Jalpaiguri', 'Samastipur', 'Arrah', 'Begusarai', 'Purnia', 'Deoghar',
    'Bokaro', 'Hazaribagh', 'Berhampur', 'Sambalpur', 'Rourkela', 'Balasore',
  ],
  west: [
    // West — Maharashtra (48), Gujarat (26), MP (29), CG (11), Goa (2)
    'Bhopal', 'Indore', 'Gwalior', 'Jabalpur', 'Ujjain', 'Sagar', 'Vidisha', 'Rajgarh', 'Dewas', 'Mandsour',
    'Ratlam', 'Dhar', 'Khargone', 'Betul', 'Hoshangabad', 'Damoh', 'Tikamgarh', 'Khajuraho', 'Satna', 'Rewa',
    'Sidhi', 'Shahdol', 'Balaghat', 'Chhindwara', 'Mandla', 'Raipur', 'Durg', 'Bilaspur', 'Korba', 'Rajnandgaon',
    'Bastar', 'Kanker', 'Janjgir-Champa', 'Mahasamund', 'Surguja',
    'Mumbai North', 'Mumbai South', 'Mumbai North West', 'Mumbai North East', 'Mumbai North Central', 'Mumbai South Central',
    'Nagpur', 'Pune', 'Nashik', 'Aurangabad', 'Kolhapur', 'Solapur', 'Akola', 'Amravati',
    'Nanded', 'Latur', 'Osmanabad', 'Buldhana', 'Yavatmal-Washim', 'Wardha', 'Raigad', 'Maval', 'Baramati',
    'Ahmadnagar', 'Shirdi', 'Nandurbar', 'Dhule', 'Jalgaon', 'Raver', 'Satara', 'Sangli', 'Hatkanangle',
    'Ahmedabad East', 'Ahmedabad West', 'Gandhinagar', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar',
    'Junagadh', 'Amreli', 'Anand', 'Kheda', 'Patan', 'Mehsana', 'Sabarkantha', 'Banaskantha', 'Navsari', 'Valsad',
    'Panaji', 'North Goa',
  ],
  east: [
    // West Bengal (42)
    'Kolkata North', 'Kolkata South', 'Howrah', 'Hooghly', 'Serampore', 'Asansol', 'Bolpur', 'Burdwan-Durgapur',
    'Krishnanagar', 'Ranaghat', 'Dum Dum', 'Barasat', 'Basirhat', 'Jadavpur', 'Diamond Harbour', 'Jaynagar',
    'Mathurapur', 'Joynagar', 'Uluberia', 'Midnapore', 'Jhargram', 'Ghatal', 'Haldia', 'Kanthi', 'Cooch Behar',
    'Alipurduars', 'Jalpaiguri', 'Darjeeling', 'Siliguri', 'Balurghat', 'Malda North', 'Malda South',
    'Jangipur', 'Murshidabad', 'Berhampore', 'Birbhum', 'Raiganj', 'Islampur', 'Bardhaman-Purba', 'Bongaon',
    'Barrackpore', 'Arambag',
    // Bihar (40)
    'Patna Sahib', 'Pataliputra', 'Ara', 'Buxar', 'Sasaram', 'Karakat', 'Jahanabad', 'Aurangabad',
    'Gaya', 'Nawada', 'Nalanda', 'Barh', 'Munger', 'Jamui', 'Banka', 'Bhagalpur', 'Kishanganj',
    'Katihar', 'Purnia', 'Madhepura', 'Supaul', 'Saharsa', 'Madhubani', 'Jhanjharpur', 'Darbhanga',
    'Muzaffarpur', 'Sitamarhi', 'Sheohar', 'Vaishali', 'Hajipur', 'Ujiarpur', 'Samastipur', 'Begusarai',
    'Khagaria', 'Gopalganj', 'Siwan', 'Maharajganj', 'Saran', 'Chapra', 'East Champaran',
    // Odisha (21)
    'Cuttack', 'Bhubaneswar', 'Puri', 'Berhampur', 'Sambalpur', 'Rourkela', 'Balasore', 'Bhadrak',
    'Kendrapara', 'Jagatsinghpur', 'Jajpur', 'Dhenkanal', 'Bolangir', 'Kalahandi', 'Nabarangpur',
    'Koraput', 'Mayurbhanj', 'Sundargarh', 'Keonjhar', 'Aska', 'Kandhamal',
    // Jharkhand (14)
    'Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro', 'Hazaribagh', 'Giridih', 'Dumka', 'Rajmahal',
    'Godda', 'Chatra', 'Koderma', 'Palamau', 'Lohardaga', 'Khunti',
    // A&N
    'Andaman & Nicobar Islands',
  ],
  northeast: [
    // All 25 NE Lok Sabha seats
    'Guwahati', 'Dibrugarh', 'Jorhat', 'Tezpur', 'Nowgong', 'Silchar', 'Lakhimpur', 'Autonomous District',
    'Karimganj', 'Barpeta', 'Kokrajhar', 'Dhubri', 'Mangaldoi', 'Nagaon',
    'Shillong', 'Tura',
    'Agartala', 'Tripura East',
    'Inner Manipur', 'Outer Manipur',
    'Aizawl',
    'Kohima', 'Nagaland',
    'Itanagar', 'Arunachal West', 'Arunachal East',
    'Gangtok', 'Sikkim',
    // Additional towns for volume
    'Dimapur', 'Imphal', 'North Lakhimpur', 'Bongaigaon', 'Mokokchung', 'Pasighat',
  ],
  south_tn: [
    // All 39 TN Lok Sabha constituencies + Puducherry
    'Tiruvallur', 'Chennai North', 'Chennai South', 'Chennai Central', 'Sriperumbudur', 'Kancheepuram',
    'Arakkonam', 'Vellore', 'Krishnagiri', 'Dharmapuri', 'Tiruvannamalai', 'Arani',
    'Viluppuram', 'Kallakurichi', 'Salem', 'Namakkal', 'Erode', 'Tiruppur',
    'Nilgiris', 'Coimbatore', 'Pollachi', 'Dindigul', 'Karur', 'Tiruchirappalli',
    'Perambalur', 'Cuddalore', 'Chidambaram', 'Mayiladuthurai', 'Nagapattinam',
    'Thanjavur', 'Sivaganga', 'Madurai', 'Virudhunagar', 'Ramanathapuram',
    'Theni', 'Tenkasi', 'Tirunelveli', 'Kanniyakumari', 'Puducherry',
  ],
  south_other: [
    // Karnataka (28)
    'Bangalore North', 'Bangalore Central', 'Bangalore South', 'Bangalore Rural', 'Chikkaballapur', 'Kolar',
    'Tumkur', 'Mandya', 'Mysore', 'Chamarajanagar', 'Dakshina Kannada', 'Udupi-Chikmagalur',
    'Hassan', 'Chikkodi', 'Belagavi', 'Bagalkot', 'Dharwad', 'Uttara Kannada', 'Haveri',
    'Davanagere', 'Shimoga', 'Bellary', 'Bijapur', 'Gulbarga', 'Raichur', 'Koppal', 'Bidar', 'Chitradurga',
    // Kerala (20)
    'Kasaragod', 'Kannur', 'Vadakara', 'Wayanad', 'Kozhikode', 'Malappuram', 'Ponnani', 'Palakkad',
    'Alathur', 'Thrissur', 'Chalakudy', 'Ernakulam', 'Idukki', 'Kottayam', 'Alappuzha',
    'Mavelikkara', 'Pathanamthitta', 'Kollam', 'Attingal', 'Thiruvananthapuram',
    // Andhra Pradesh (25)
    'Araku', 'Srikakulam', 'Vizianagaram', 'Visakhapatnam', 'Anakapalli', 'Kakinada', 'Amalapuram',
    'Rajahmundry', 'Narsapuram', 'Eluru', 'Machilipatnam', 'Vijayawada', 'Guntur', 'Narasaraopet',
    'Bapatla', 'Ongole', 'Nandyal', 'Kurnool', 'Kadapa', 'Nellore', 'Tirupati', 'Rajampet',
    'Chittoor', 'Hindupur', 'Anantapur',
    // Telangana (17)
    'Adilabad', 'Peddapalle', 'Karimnagar', 'Nizamabad', 'Zahirabad', 'Medak', 'Malkajgiri',
    'Secunderabad', 'Hyderabad', 'Chevella', 'Mahbubnagar', 'Nagarkurnool', 'Nalgonda',
    'Bhongir', 'Warangal', 'Mahabubabad', 'Khammam',
  ],
};

const ALL_ZONE_IDS: ZoneId[] = ['north', 'east', 'west', 'northeast', 'south_tn', 'south_other'];

// Return all cities, putting other-zone cities first so the simulation
// flavour of "representing a constituency outside your own region" is
// preserved for the majority of delegates even in large events.
function citiesFromOtherZones(eventZone: ZoneId | null): string[] {
  const others = eventZone ? ALL_ZONE_IDS.filter(z => z !== eventZone) : ALL_ZONE_IDS;
  const own    = eventZone ? [eventZone] : [];
  return [...others, ...own].flatMap(z => ZONE_CITIES[z]);
}

// No directional suffixes — each city name is used as-is.
// If the pool is exhausted (events > ~430 students) the picker appends "(2)", "(3)" etc.
function buildConstituencyPool(cities: string[]): string[] {
  return [...cities];
}

// Returns a function that hands out the next unused constituency from the
// pool on each call, guaranteeing no duplicates within the event. `used`
// should be pre-seeded with constituencies already assigned in this event.
function createConstituencyPicker(pool: string[], used: Set<string>) {
  let idx = 0;
  return function next(): string {
    while (idx < pool.length && used.has(pool[idx])) idx++;
    const cycle = Math.floor(idx / pool.length);
    const constituency = cycle === 0 ? pool[idx] : `${pool[idx % pool.length]} (${cycle + 1})`;
    used.add(constituency);
    idx++;
    return constituency;
  };
}

// Easy-to-remember 6-digit numeric password — students keep this permanently.
// It also doubles as their "login code" (profiles.login_code), so it must be
// unique across every student. `used` should be pre-seeded with every
// login_code already in the database.
function generateLoginCode(used: Set<string>): string {
  let code: string;
  do {
    code = Math.floor(100000 + Math.random() * 900000).toString();
  } while (used.has(code));
  used.add(code);
  return code;
}

// Round-robin distributes committee + party (and ruling/opposition
// alignment) across every student in the event, in serial-number order.
// Mirrors public.reassign_event_committees_parties(), done here with the
// service-role client so it doesn't require a super-admin JWT.
//
// Students are grouped by their target committee/party so each group is
// written with a single `.update().in('user_id', [...])` call — O(committees
// + parties) round trips instead of O(students). With hundreds of students
// across many import batches, one-update-per-student was slow enough to
// exceed the function's execution time limit and hang the client request.
// Only assigns party/committee to students who don't have one yet (party_number = 0).
// Never reshuffles existing students — that caused chaos when reimporting.
async function reassignCommitteesAndParties(supabaseAdmin: any, eventId: string) {
  const { data: committees } = await supabaseAdmin
    .from('event_committees').select('name, display_order').eq('event_id', eventId).order('display_order');
  const { data: parties } = await supabaseAdmin
    .from('event_parties').select('name, display_order, alignment').eq('event_id', eventId).order('display_order');

  // Only process students who haven't been assigned a party yet
  const { data: students } = await supabaseAdmin
    .from('profiles').select('user_id, position, party_number, committee')
    .eq('event_id', eventId).eq('user_type', 'student')
    .order('serial_number');

  const unassigned = (students ?? []).filter((s: any) =>
    !['Admin Student', 'Journalist'].includes(s.position) &&
    (!s.party_number || s.party_number === 0)
  );

  if (unassigned.length === 0) return; // all students already have assignments — nothing to do

  // Determine the next party/committee slot by counting already-assigned students
  const alreadyAssigned = (students ?? []).filter((s: any) =>
    !['Admin Student', 'Journalist'].includes(s.position) &&
    s.party_number && s.party_number > 0
  ).length;

  if (parties && parties.length > 0) {
    for (let i = 0; i < unassigned.length; i++) {
      const slot = (alreadyAssigned + i) % parties.length;
      const party = parties[slot];
      const alignment: string = party.alignment ?? 'opposition';
      await supabaseAdmin.from('profiles').update({
        party_name: party.name,
        party_number: slot + 1,
        party_alignment: alignment,
      }).eq('user_id', unassigned[i].user_id);
    }
  }

  if (committees && committees.length > 0) {
    for (let i = 0; i < unassigned.length; i++) {
      const slot = (alreadyAssigned + i) % committees.length;
      await supabaseAdmin.from('profiles').update({
        committee: committees[slot].name,
      }).eq('user_id', unassigned[i].user_id);
    }
  }
}

// Adds any newly-seen school names to the event's school directory so the
// organizer doesn't have to add them manually afterwards.
async function autoAddSchools(supabaseAdmin: any, eventId: string, schoolNames: Set<string>) {
  if (schoolNames.size === 0) return;

  const { data: existingSchools } = await supabaseAdmin
    .from('event_schools').select('name').eq('event_id', eventId);
  const existingLower = new Set((existingSchools ?? []).map((s: any) => s.name.toLowerCase()));

  const { data: maxOrderRow } = await supabaseAdmin
    .from('event_schools').select('display_order').eq('event_id', eventId)
    .order('display_order', { ascending: false }).limit(1).maybeSingle();
  let nextOrder = (maxOrderRow?.display_order ?? -1) + 1;

  const toInsert = [...schoolNames]
    .filter(name => !existingLower.has(name.toLowerCase()))
    .map(name => ({ event_id: eventId, name, display_order: nextOrder++ }));

  if (toInsert.length > 0) {
    await supabaseAdmin.from('event_schools').insert(toInsert);
  }
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Create admin client with service role key
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      {
        auth: {
          autoRefreshToken: false,
          persistSession: false
        }
      }
    );

    const { students, mode = 'full', event_id, is_last_batch = true } = await req.json();
    const results: {
      success: number;
      failed: number;
      errors: string[];
      credentials: Array<{ serialNumber: number; name: string; school: string; email: string; phone?: string; password: string }>;
    } = { success: 0, failed: 0, errors: [], credentials: [] };
    // NOTE: credentials[].email is the real email if provided, or '' if not.
    // The synthetic auth email ({loginCode}@noemail.yip.internal) is stored in
    // auth + profiles.email internally but never returned to the client.

    console.log(`Import mode: ${mode}`);

    // Handle scores-only import mode
    if (mode === 'scores-only') {
      for (const student of students as StudentData[]) {
        try {
          // Validate required fields for scores-only mode
          if (!student.serialNumber) {
            results.errors.push(`Row skipped: Missing serial number`);
            results.failed++;
            continue;
          }

          // Find existing profile by serial number
          const { data: existingProfile, error: profileError } = await supabaseAdmin
            .from('profiles')
            .select('user_id, name')
            .eq('serial_number', student.serialNumber)
            .single();

          if (profileError || !existingProfile) {
            results.errors.push(`Serial ${student.serialNumber}: Student not found`);
            results.failed++;
            continue;
          }

          // Update only pre-event scores
          const { error: updateError } = await supabaseAdmin
            .from('profiles')
            .update({
              preevent_scores: student.preeventScores ?? null,
              updated_at: new Date().toISOString()
            })
            .eq('user_id', existingProfile.user_id);

          if (updateError) {
            results.errors.push(`${existingProfile.name}: Failed to update scores - ${updateError.message}`);
            results.failed++;
            continue;
          }

          console.log(`Updated scores for: ${existingProfile.name} (Serial: ${student.serialNumber})`);
          results.success++;

        } catch (error) {
          console.error('Error processing student:', error);
          results.errors.push(`Serial ${student.serialNumber}: ${error.message}`);
          results.failed++;
        }
      }

      return new Response(JSON.stringify(results), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      });
    }

    // ── Full import mode ──────────────────────────────────────────
    // Reject immediately if no event_id — students would be created without
    // an event assignment and never appear in any organizer's student list.
    if (mode === 'full' && !event_id) {
      return new Response(JSON.stringify({
        success: 0,
        failed: (students as StudentData[]).length,
        errors: ['Import rejected: your account is not assigned to an event. Contact your administrator.'],
        credentials: [],
      }), { headers: { ...corsHeaders, 'Content-Type': 'application/json' } });
    }

    // Look up the event's state/city so new students inherit them, and so
    // constituencies can be allocated from the opposite zone.
    let eventState: string | null = null;
    let eventCity: string | null = null;
    if (event_id) {
      const { data: eventRow } = await supabaseAdmin
        .from('events').select('state, city').eq('id', event_id).maybeSingle();
      eventState = eventRow?.state ?? null;
      eventCity = eventRow?.city ?? null;
    }

    // Determine the next serial number to assign to new students.
    const { data: maxSerialRow } = await supabaseAdmin
      .from('profiles').select('serial_number').order('serial_number', { ascending: false }).limit(1).maybeSingle();
    let nextSerial = (maxSerialRow?.serial_number ?? 0) + 1;

    // Build a constituency picker scoped to this event: a pool drawn from
    // every zone EXCEPT the event's own zone, pre-seeded with constituencies
    // already in use so new students never get a duplicate within the event.
    const eventZone = getZoneId(eventState);
    const constituencyPool = buildConstituencyPool(citiesFromOtherZones(eventZone));
    let usedConstituenciesQuery = supabaseAdmin
      .from('profiles').select('constituency').eq('user_type', 'student').not('constituency', 'is', null);
    usedConstituenciesQuery = event_id
      ? usedConstituenciesQuery.eq('event_id', event_id)
      : usedConstituenciesQuery.is('event_id', null);
    const { data: existingConstituencyRows } = await usedConstituenciesQuery;
    const usedConstituencies = new Set<string>((existingConstituencyRows ?? []).map((r: any) => r.constituency));
    const nextConstituency = createConstituencyPicker(constituencyPool, usedConstituencies);

    // login_code must be unique across ALL students (not just this event),
    // since the "login with code" flow looks up an account by code alone.
    const { data: existingCodeRows } = await supabaseAdmin
      .from('profiles').select('login_code').not('login_code', 'is', null);
    const usedLoginCodes = new Set<string>((existingCodeRows ?? []).map((r: any) => r.login_code));

    const newSchools = new Set<string>();

    for (const student of students as StudentData[]) {
      try {
        const name  = (student.name  ?? '').toString().trim();
        const school = (student.school ?? '').toString().trim() || 'Independent';
        const email = (student.email ?? '').toString().trim().toLowerCase();
        const phone = (student.phone ?? '').toString().trim();

        if (!name) {
          results.errors.push(`Row skipped: Missing Name`);
          results.failed++;
          continue;
        }

        // Re-upload safe: match by real email if provided, else by name within event.
        // Fallback: if no match in-event, check for an unclaimed student (null event_id)
        // with the same name — this reclaims accounts created during a failed first import
        // that ran without a valid event_id, avoiding duplicate auth users.
        let existingProfile: { user_id: string } | null = null;
        if (email) {
          const { data } = await supabaseAdmin
            .from('profiles').select('user_id').ilike('email', email).maybeSingle();
          existingProfile = data;
        } else if (event_id) {
          const { data: inEvent } = await supabaseAdmin
            .from('profiles').select('user_id')
            .ilike('name', name).eq('event_id', event_id).eq('user_type', 'student').maybeSingle();
          existingProfile = inEvent;

          // No orphan claim — too risky to match by name alone across all events.
          // Orphan cleanup is handled by the Delete All function before reimport.
        }

        if (existingProfile) {
          const updates: any = { name, school, phone: phone || null };
          if (event_id) updates.event_id = event_id;
          // Update real email only if provided (don't overwrite synthetic email)
          if (email) updates.email = email;

          const { error: updateProfileError } = await supabaseAdmin
            .from('profiles').update(updates).eq('user_id', existingProfile.user_id);

          if (updateProfileError) {
            results.errors.push(`${name}: Failed to update profile - ${updateProfileError.message}`);
            results.failed++;
            continue;
          }

          // Return existing credentials so the organizer's download sheet covers
          // ALL students, not just newly created ones (handles re-import case).
          const { data: existingData } = await supabaseAdmin
            .from('profiles')
            .select('serial_number, login_code, email')
            .eq('user_id', existingProfile.user_id)
            .maybeSingle();

          if (existingData?.login_code) {
            const displayEmail = email
              || (existingData.email && !existingData.email.endsWith('@noemail.yip.internal')
                  ? existingData.email : '');
            results.credentials.push({
              serialNumber: existingData.serial_number ?? 0,
              name,
              school,
              email: displayEmail,
              password: existingData.login_code,
            });
          }

          results.success++;
        } else {
          const password = generateLoginCode(usedLoginCodes);
          // When no real email, generate a synthetic one so Supabase auth
          // can create the account. Code login resolves email by login_code
          // so students never need to know or type this synthetic address.
          const loginEmail = email || `${password}@noemail.yip.internal`;

          const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
            email: loginEmail,
            password,
            email_confirm: true,
          });

          if (authError) {
            results.errors.push(`${name}: Failed to create auth user - ${authError.message}`);
            results.failed++;
            continue;
          }

          const serialNumber = nextSerial++;
          const constituency = nextConstituency();

          const profileData: any = {
            user_id: authData.user.id,
            serial_number: serialNumber,
            name,
            school,
            phone: phone || null,
            email: loginEmail,
            position: 'Member of Parliament',
            party_number: 0,
            party_alignment: 'non_aligned',
            constituency,
            login_code: password,
            state: eventState,
            city: eventCity,
            user_type: 'student',
            ...(event_id ? { event_id } : {}),
          };

          const { error: profileError } = await supabaseAdmin
            .from('profiles').insert(profileData);

          if (profileError) {
            await supabaseAdmin.auth.admin.deleteUser(authData.user.id);
            results.errors.push(`${name}: Failed to create profile - ${profileError.message}`);
            results.failed++;
            continue;
          }

          // Return '' for email when no real email — client uses this to decide
          // whether to include this student in bulk email.
          results.credentials.push({ serialNumber, name, school, email, phone: phone || undefined, password });
          newSchools.add(school);
          results.success++;
        }
      } catch (error) {
        results.errors.push(`${student.name}: Unexpected error - ${error instanceof Error ? error.message : 'Unknown error'}`);
        results.failed++;
      }
    }

    if (event_id) {
      await autoAddSchools(supabaseAdmin, event_id, newSchools);
      // Reassigning committees/parties re-processes the whole event roster,
      // so only do it once after the final batch — not after every batch.
      if (is_last_batch) {
        await reassignCommitteesAndParties(supabaseAdmin, event_id);
      }
    }

    return new Response(JSON.stringify(results), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error('Error in bulk-import-students function:', error);
    return new Response(JSON.stringify({
      success: 0,
      failed: 0,
      errors: [error instanceof Error ? error.message : 'Unknown error'],
      credentials: [],
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
