import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.56.0';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

// Simplified full-import row: only Name, School, Email, Phone come from the
// sheet. Everything else (login, password, serial number, seat role, party,
// committee, constituency, state/city) is generated by the app.
interface StudentData {
  name: string;
  school?: string;
  email: string;
  phone?: string;
  // scores-only mode fields
  serialNumber?: number;
  preeventScores?: number;
}

// States that fall in the south_tn / south_other zones (see src/lib/regions.ts).
// Students at an event in one of these states get a "northern" constituency,
// and vice versa — purely flavour data for the simulation.
const SOUTH_STATES = new Set([
  'Tamil Nadu', 'Puducherry', 'Telangana', 'Karnataka', 'Kerala', 'Andhra Pradesh', 'Lakshadweep',
]);

const NORTHERN_CONSTITUENCIES = [
  'New Delhi', 'Amritsar', 'Lucknow', 'Varanasi', 'Jaipur', 'Chandigarh',
  'Patna Sahib', 'Kolkata Dakshin', 'Bhubaneswar', 'Ranchi', 'Indore',
  'Bhopal', 'Mumbai North', 'Pune', 'Ahmedabad East', 'Panaji', 'Shimla',
  'Dehradun', 'Guwahati', 'Shillong',
];

const SOUTHERN_CONSTITUENCIES = [
  'Chennai South', 'Madurai', 'Coimbatore', 'Puducherry', 'Bengaluru Central',
  'Mysuru', 'Hyderabad', 'Warangal', 'Visakhapatnam', 'Vijayawada',
  'Thiruvananthapuram', 'Ernakulam', 'Mangaluru', 'Tiruchirappalli',
  'Kanyakumari', 'Hubli-Dharwad', 'Kurnool', 'Kozhikode', 'Salem', 'Madikeri',
];

function getCrossZoneConstituency(state: string | null | undefined, index: number): string {
  const pool = state && SOUTH_STATES.has(state) ? NORTHERN_CONSTITUENCIES : SOUTHERN_CONSTITUENCIES;
  return pool[((index % pool.length) + pool.length) % pool.length];
}

// Easy-to-remember 6-digit numeric password — students keep this permanently.
function generatePassword(): string {
  return Math.floor(100000 + Math.random() * 900000).toString();
}

// Round-robin distributes committee + party (and ruling/opposition
// alignment) across every student in the event, in serial-number order.
// Mirrors public.reassign_event_committees_parties(), done here with the
// service-role client so it doesn't require a super-admin JWT.
async function reassignCommitteesAndParties(supabaseAdmin: any, eventId: string) {
  const { data: committees } = await supabaseAdmin
    .from('event_committees').select('name, display_order').eq('event_id', eventId).order('display_order');
  const { data: parties } = await supabaseAdmin
    .from('event_parties').select('name, display_order').eq('event_id', eventId).order('display_order');
  const { data: students } = await supabaseAdmin
    .from('profiles').select('user_id, position')
    .eq('event_id', eventId).eq('user_type', 'student')
    .order('serial_number');

  const eligible = (students ?? []).filter((s: any) => !['Admin Student', 'Journalist'].includes(s.position));

  if (committees && committees.length > 0) {
    for (let i = 0; i < eligible.length; i++) {
      const committee = committees[i % committees.length].name;
      await supabaseAdmin.from('profiles').update({ committee }).eq('user_id', eligible[i].user_id);
    }
  }

  if (parties && parties.length > 0) {
    const rulingThreshold = Math.floor(parties.length / 2) + 1;
    for (let i = 0; i < eligible.length; i++) {
      const idx = i % parties.length;
      const partyNumber = idx + 1;
      const alignment = partyNumber <= rulingThreshold ? 'ruling_party' : 'opposition';
      await supabaseAdmin.from('profiles').update({
        party_name: parties[idx].name,
        party_number: partyNumber,
        party_alignment: alignment,
      }).eq('user_id', eligible[i].user_id);
    }
  }
}

// Adds any newly-seen school names to the event's school directory so the
// organizer doesn't have to add them manually afterwards.
async function autoAddSchools(supabaseAdmin: any, eventId: string, schoolNames: Set<string>) {
  if (schoolNames.size === 0) return;

  const { data: existingSchools } = await supabaseAdmin
    .from('event_schools').select('name').eq('event_id', eventId);
  const existingLower = new Set((existingSchools ?? []).map((s: any) => s.name.toLowerCase()));

  const { data: maxOrderRow } = await supabaseAdmin
    .from('event_schools').select('display_order').eq('event_id', eventId)
    .order('display_order', { ascending: false }).limit(1).maybeSingle();
  let nextOrder = (maxOrderRow?.display_order ?? -1) + 1;

  const toInsert = [...schoolNames]
    .filter(name => !existingLower.has(name.toLowerCase()))
    .map(name => ({ event_id: eventId, name, display_order: nextOrder++ }));

  if (toInsert.length > 0) {
    await supabaseAdmin.from('event_schools').insert(toInsert);
  }
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Create admin client with service role key
    const supabaseAdmin = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      {
        auth: {
          autoRefreshToken: false,
          persistSession: false
        }
      }
    );

    const { students, mode = 'full', event_id } = await req.json();
    const results: {
      success: number;
      failed: number;
      errors: string[];
      credentials: Array<{ serialNumber: number; name: string; school: string; email: string; phone?: string; password: string }>;
    } = { success: 0, failed: 0, errors: [], credentials: [] };

    console.log(`Import mode: ${mode}`);

    // Handle scores-only import mode
    if (mode === 'scores-only') {
      for (const student of students as StudentData[]) {
        try {
          // Validate required fields for scores-only mode
          if (!student.serialNumber) {
            results.errors.push(`Row skipped: Missing serial number`);
            results.failed++;
            continue;
          }

          // Find existing profile by serial number
          const { data: existingProfile, error: profileError } = await supabaseAdmin
            .from('profiles')
            .select('user_id, name')
            .eq('serial_number', student.serialNumber)
            .single();

          if (profileError || !existingProfile) {
            results.errors.push(`Serial ${student.serialNumber}: Student not found`);
            results.failed++;
            continue;
          }

          // Update only pre-event scores
          const { error: updateError } = await supabaseAdmin
            .from('profiles')
            .update({
              preevent_scores: student.preeventScores ?? null,
              updated_at: new Date().toISOString()
            })
            .eq('user_id', existingProfile.user_id);

          if (updateError) {
            results.errors.push(`${existingProfile.name}: Failed to update scores - ${updateError.message}`);
            results.failed++;
            continue;
          }

          console.log(`Updated scores for: ${existingProfile.name} (Serial: ${student.serialNumber})`);
          results.success++;

        } catch (error) {
          console.error('Error processing student:', error);
          results.errors.push(`Serial ${student.serialNumber}: ${error.message}`);
          results.failed++;
        }
      }

      return new Response(JSON.stringify(results), {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      });
    }

    // ── Full import mode ──────────────────────────────────────────
    // Look up the event's state/city so new students inherit them, and so
    // constituencies can be allocated from the opposite zone.
    let eventState: string | null = null;
    let eventCity: string | null = null;
    if (event_id) {
      const { data: eventRow } = await supabaseAdmin
        .from('events').select('state, city').eq('id', event_id).maybeSingle();
      eventState = eventRow?.state ?? null;
      eventCity = eventRow?.city ?? null;
    }

    // Determine the next serial number to assign to new students.
    const { data: maxSerialRow } = await supabaseAdmin
      .from('profiles').select('serial_number').order('serial_number', { ascending: false }).limit(1).maybeSingle();
    let nextSerial = (maxSerialRow?.serial_number ?? 0) + 1;

    const newSchools = new Set<string>();

    for (const student of students as StudentData[]) {
      try {
        const name = (student.name ?? '').toString().trim();
        const school = (student.school ?? '').toString().trim();
        const email = (student.email ?? '').toString().trim().toLowerCase();
        const phone = (student.phone ?? '').toString().trim();

        if (!name || !school || !email) {
          results.errors.push(`Row skipped: Missing required field (Name, School, or Email) for "${name || email || 'unknown'}"`);
          results.failed++;
          continue;
        }

        // Re-upload safe: match existing students by email
        const { data: existingProfile } = await supabaseAdmin
          .from('profiles')
          .select('user_id')
          .ilike('email', email)
          .maybeSingle();

        if (existingProfile) {
          const { error: updateProfileError } = await supabaseAdmin
            .from('profiles')
            .update({
              name,
              school,
              phone: phone || null,
              ...(event_id ? { event_id } : {}),
            })
            .eq('user_id', existingProfile.user_id);

          if (updateProfileError) {
            results.errors.push(`${name}: Failed to update profile - ${updateProfileError.message}`);
            results.failed++;
            continue;
          }

          results.success++;
        } else {
          const password = generatePassword();

          const { data: authData, error: authError } = await supabaseAdmin.auth.admin.createUser({
            email,
            password,
            email_confirm: true,
          });

          if (authError) {
            results.errors.push(`${name}: Failed to create auth user - ${authError.message}`);
            results.failed++;
            continue;
          }

          const serialNumber = nextSerial++;
          const constituency = getCrossZoneConstituency(eventState, serialNumber);

          const profileData: any = {
            user_id: authData.user.id,
            serial_number: serialNumber,
            name,
            school,
            phone: phone || null,
            email,
            position: 'Member of Parliament',
            party_number: 0,
            party_alignment: 'non_aligned',
            constituency,
            state: eventState,
            city: eventCity,
            user_type: 'student',
            ...(event_id ? { event_id } : {}),
          };

          const { error: profileError } = await supabaseAdmin
            .from('profiles')
            .insert(profileData);

          if (profileError) {
            // Roll back the auth user so re-upload doesn't collide on email
            await supabaseAdmin.auth.admin.deleteUser(authData.user.id);
            results.errors.push(`${name}: Failed to create profile - ${profileError.message}`);
            results.failed++;
            continue;
          }

          results.credentials.push({ serialNumber, name, school, email, phone: phone || undefined, password });
          newSchools.add(school);
          results.success++;
        }
      } catch (error) {
        results.errors.push(`${student.name}: Unexpected error - ${error instanceof Error ? error.message : 'Unknown error'}`);
        results.failed++;
      }
    }

    if (event_id) {
      await autoAddSchools(supabaseAdmin, event_id, newSchools);
      await reassignCommitteesAndParties(supabaseAdmin, event_id);
    }

    return new Response(JSON.stringify(results), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error('Error in bulk-import-students function:', error);
    return new Response(JSON.stringify({
      success: 0,
      failed: 0,
      errors: [error instanceof Error ? error.message : 'Unknown error'],
      credentials: [],
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});
